### ISSUE TITLE
Can't seem to install it, user error? (yes, needed cmd)

### ISSUE THREAD

**Issue by castlez** [JVMartin/bash-here#1]
![image](https://cloud.githubusercontent.com/assets/4977575/17393080/2aca363a-59d6-11e6-8619-0da1f7b635cf.png)

**Comment by castlez** [comment]
its because i was trying to launch this in bash, not command prompt

**Comment by JVMartin** [comment]
Thanks for the issue man - I should make it clearer that these are windows registries.  :+1:
